### ISSUE TITLE
network test needs to check for internet availability

### ISSUE THREAD

**Issue by karenetheridge** [woodruffw/WebService-UrbanDictionary#2]
This failure here: http://www.cpantesters.org/cpan/report/50fce128-b292-11e4-adfb-e2d3ebda7229
suggests that the test should be using Test::RequiresInternet.

**Comment by woodruffw** [comment]
Yes, that's a much better solution than what I did.
Applied in bb7294c83b5f71ebfcd93242383d947b68dc84d4.

Thank you!
